apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: conf
  files:
  - conf/groups.yml
- name: import
  files:
  - conf/import/battle_conf.txt
  - conf/import/char_conf.txt
  - conf/import/inter_conf.txt
  - conf/import/map_conf.txt
- name: npc
  files:
  - npc/scripts_custom.conf
  - npc/healernpc.txt
  - npc/resetnpc.txt
  - npc/warpernpc.txt