---
apiVersion: v1
kind: Service
metadata:
  name: rathena
spec:
  type: LoadBalancer
  selector:
    app: rathena
  ports:
  - name: login
    port: 6900
    targetPort: 6900
  - name: char
    port: 6121
    targetPort: 6121
  - name: map
    port: 5121
    targetPort: 5121