apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-ro-robot
  labels:
    app: open-ro-robot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-ro-robot
  template:
    metadata:
      labels:
        app: open-ro-robot
    spec:
      containers:
      - name: robot
        image: ttl.sh/5d03e598-2c51-11ed-8c1e-00155d6c28c3:6h
        imagePullPolicy: IfNotPresent
        command: [./robot]
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                key: TELEGRAM_BOT_TOKEN
                name: open-ro-robot
          - name: TELEGRAM_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                key: TELEGRAM_WEBHOOK_URL
                name: open-ro-robot
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 5555
            name: http
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: "/health"
            port: 5555
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: "/health"
            port: 5555
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
